#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PWMeditation.Resource", IsApplication=true)]

namespace PWMeditation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int bLoadRoles = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int bSave = 2131034124;
			
			// aapt resource value: 0x7f050019
			public const int bSaveServer = 2131034137;
			
			// aapt resource value: 0x7f05000b
			public const int cbAutoMessage = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int cbForce = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int cbShowOnline = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int etAutoMessage = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int etLogin = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int etPassword = 2131034116;
			
			// aapt resource value: 0x7f050018
			public const int etServerAddressSettings = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int etServerNameSettings = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int pbExperience = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int spinAccounts = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int spinSelectedRole = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int spinSelectedServer = 2131034113;
			
			// aapt resource value: 0x7f050015
			public const int spinServerListSettings = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int textView3 = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int tvExperience = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int tvLevel = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int tvMeditationHigh = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int tvMeditationLow = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int tvMeditationStatus = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int tvMeditationToday = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountSettings = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ServerSettings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int account = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int add = 2130968579;
			
			// aapt resource value: 0x7f040025
			public const int app_name = 2130968613;
			
			// aapt resource value: 0x7f040022
			public const int cancel = 2130968610;
			
			// aapt resource value: 0x7f040000
			public const int connect = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int connected = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int connecting = 2130968585;
			
			// aapt resource value: 0x7f040012
			public const int days = 2130968594;
			
			// aapt resource value: 0x7f040024
			public const int default_automessage = 2130968612;
			
			// aapt resource value: 0x7f040004
			public const int delete = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int disconnect = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int disconnected = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int edit = 2130968581;
			
			// aapt resource value: 0x7f04000e
			public const int experience = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int hours = 2130968595;
			
			// aapt resource value: 0x7f04000c
			public const int in_the_world = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int level = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int meditation = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int meditation_high = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int meditation_low = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int minutes = 2130968596;
			
			// aapt resource value: 0x7f040023
			public const int ok = 2130968611;
			
			// aapt resource value: 0x7f04000a
			public const int relogin = 2130968586;
			
			// aapt resource value: 0x7f040021
			public const int save = 2130968609;
			
			// aapt resource value: 0x7f040015
			public const int seconds = 2130968597;
			
			// aapt resource value: 0x7f040006
			public const int settings = 2130968582;
			
			// aapt resource value: 0x7f04001b
			public const int settings_account_automessage = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int settings_account_force_auth = 2130968604;
			
			// aapt resource value: 0x7f04001a
			public const int settings_account_load = 2130968602;
			
			// aapt resource value: 0x7f040017
			public const int settings_account_login = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int settings_account_password = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int settings_account_role = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int settings_account_server = 2130968598;
			
			// aapt resource value: 0x7f04001d
			public const int settings_account_show_online = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int settings_account_use_automessage = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int settings_server_address = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int settings_server_name = 2130968607;
			
			// aapt resource value: 0x7f04000f
			public const int today = 2130968591;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
